[package]
name = "typemake"
description = "A workflow manager abstracting from files"
license = "MIT"
version = "0.1.0-alpha.0"
edition = "2018"

[dependencies]
nom = "7"
clap = "3.0.0-beta.4"
log = "0.4"
simplelog = "0.10"
error-chain = "0.12"